### ISSUE TITLE
[Gateway] 카카오 토큰 요청 API 질문

### ISSUE THREAD

**Issue by wlsdhr0831** [cbnu12/koc-gateway#9]
## 요청
![image](https://github.com/cbnu12/koc-gateway/assets/37607649/cfe1c23a-348a-4b43-be77-11faf5fb05a8)

## 응답
![image](https://github.com/cbnu12/koc-gateway/assets/37607649/fc0251a8-a782-4d95-b537-b3c1d6445633)
![image](https://github.com/cbnu12/koc-gateway/assets/37607649/7d05bb54-1a6b-4d5c-b1f8-07fab6dbdec1)

API 자체는 200 으로 왔는대
토큰 발급하는 API 응답이 이렇게 떨어지는데 혹시 이유를 알 수 있을까용..?
뭐를 잘못 보내서 400이 떨어지는건지 모르겟어요..

**Comment by hgs6424** [comment]
user쪽에서 확인 필요해서 user로 이관
